import { describe, it, expect } from "vitest";
import { CamFrameStream } from "./cam-frame-stream";

/** 6-second testsrc, 30 fps, keyframe every 1 second (= 6 keyframes
 *  at t = 0, 1, 2, 3, 4, 5). 160×120 H.264. Generated by
 *  `ffmpeg -force_key_frames "expr:gte(t,n_forced*1)" -g 30
 *   -sc_threshold 0`. Used to exercise GOP-aware seek behavior. */
const FIXTURE_URL = "/__test_fixtures__/video-multi-keyframe.mp4";

async function fetchFixture(): Promise<Blob> {
  const r = await fetch(FIXTURE_URL);
  return await r.blob();
}

describe("CamFrameStream — linear forward (regression)", () => {
  it("monotonic small advances do not trigger any seek", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      // Walk forward in 33ms steps from t=100ms to t=900ms — all within
      // the first GOP, no seek should fire.
      for (let tMs = 100; tMs <= 900; tMs += 33) {
        const f = await stream.frameAtOrBefore(tMs * 1000);
        expect(f).not.toBeNull();
      }
      expect(stream.seeks).toBe(0);
    } finally {
      stream.close();
    }
  });

  it("walking the entire file forward returns increasing timestamps", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      let prev = -1;
      for (let tMs = 100; tMs <= 5_500; tMs += 100) {
        const f = await stream.frameAtOrBefore(tMs * 1000);
        expect(f).not.toBeNull();
        expect(f!.timestamp).toBeGreaterThanOrEqual(prev);
        prev = f!.timestamp;
      }
    } finally {
      stream.close();
    }
  });
});

describe("CamFrameStream — explicit seekTo", () => {
  it("seekTo(targetUs) lands on or before target", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      // Seek to t=3.5s. Expected first frame timestamp ≤ 3.5s.
      await stream.seekTo(3_500_000);
      const f = await stream.frameAtOrBefore(3_500_000);
      expect(f).not.toBeNull();
      expect(f!.timestamp).toBeLessThanOrEqual(3_500_000);
      // And it should be reasonably close to 3.5s — i.e. on/after the
      // 3s keyframe (not all the way back to 0).
      expect(f!.timestamp).toBeGreaterThanOrEqual(3_000_000);
    } finally {
      stream.close();
    }
  });

  it("multiple seeks back-and-forth all return valid frames", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      const targets = [1_500_000, 4_500_000, 500_000, 5_500_000, 2_500_000];
      for (const t of targets) {
        await stream.seekTo(t);
        const f = await stream.frameAtOrBefore(t);
        expect(f).not.toBeNull();
        expect(f!.timestamp).toBeLessThanOrEqual(t);
      }
    } finally {
      stream.close();
    }
  });
});

describe("CamFrameStream — auto-seek on jumps", () => {
  it("backward jump auto-seeks (vs. previous: would stall or return null)", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      // Walk to ~4s then jump back to ~1s.
      const f1 = await stream.frameAtOrBefore(4_500_000);
      expect(f1).not.toBeNull();
      const seeksBefore = stream.seeks;
      const f2 = await stream.frameAtOrBefore(1_500_000);
      expect(f2).not.toBeNull();
      expect(f2!.timestamp).toBeLessThanOrEqual(1_500_000);
      // A seek must have fired to satisfy the backward jump.
      expect(stream.seeks).toBeGreaterThan(seeksBefore);
    } finally {
      stream.close();
    }
  });

  it("large forward jump (>2s budget) triggers a seek", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      // First call at t=0.3s. Second jumps to t=4.5s — delta = 4.2s > 2s budget.
      const f1 = await stream.frameAtOrBefore(300_000);
      expect(f1).not.toBeNull();
      const seeksBefore = stream.seeks;
      const f2 = await stream.frameAtOrBefore(4_500_000);
      expect(f2).not.toBeNull();
      expect(f2!.timestamp).toBeLessThanOrEqual(4_500_000);
      expect(f2!.timestamp).toBeGreaterThanOrEqual(4_000_000);
      expect(stream.seeks).toBeGreaterThan(seeksBefore);
    } finally {
      stream.close();
    }
  });

  it("first call past the budget seeks instead of decoding from sample 0", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      // First-ever call at t=4.5s — should seek (target > 2s budget vs. start).
      const f = await stream.frameAtOrBefore(4_500_000);
      expect(f).not.toBeNull();
      expect(f!.timestamp).toBeGreaterThanOrEqual(4_000_000);
      expect(stream.seeks).toBe(1);
    } finally {
      stream.close();
    }
  });

  it("small forward step within budget does NOT seek", async () => {
    const blob = await fetchFixture();
    const stream = await CamFrameStream.create(blob);
    try {
      const f1 = await stream.frameAtOrBefore(500_000);
      expect(f1).not.toBeNull();
      const seeksBefore = stream.seeks;
      // Step forward by 1.5s — within the 2s budget.
      const f2 = await stream.frameAtOrBefore(2_000_000);
      expect(f2).not.toBeNull();
      expect(stream.seeks).toBe(seeksBefore);
    } finally {
      stream.close();
    }
  });
});
